format = """
â”Œ $username\
$directory\
$git_branch \
$git_status\
$python
â””â¯ 
"""

[username]
show_always = true
style_user = "bold red"

[directory]
format = "[ğŸ“ $path]($style)[$read_only]($read_only_style) "
style = "bold yellow"

[git_branch]
always_show_remote = true
format = "[$symbol $branch]($style)"
symbol = "ğŸŒ¿"
style = "bold green"

[git_status]
style = "white"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
style = "bold cyan"
